name: Conditional Workflow

on:
  push:
    branches:
      - master

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Script
        continue-on-error: true
        id: run-script
        run: python sum.py
  
  conditional-job-1:
    needs: run-python
    if: ${{ steps.run-script.outputs.code == '0' }}
    runs-on: ubuntu-latest
    
    steps: 
      - name: Conditional Job1
        run: echo "Job 1 is running"

  conditional-job-2:
    needs: run-python
    if: ${{ steps.run-script.outputs.code != '1' }}
    runs-on: ubuntu-latest

    steps: 
      - name: Conditional Job2
        run: echo "Job 2 is running"
  