name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First Number'
        required: true
        type: number
      num2:
        description: 'Second Number'
        required: true
        type: number

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Script
        continue-on-error: true
        id: run-script
        run: python sum.py ${{ github.event.inputs.num1 }} ${{ github.event.inputs.num2 }}
  
  conditional-job-1:
    needs: run-python
    if: failure() 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Conditional Job1
        run: echo "Job 1 is running"

  conditional-job-2:
    needs: run-python
    if: success()
    runs-on: ubuntu-latest

    steps: 
      - name: Conditional Job2
        run: echo "Job 2 is running"
  
