name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First Number'
        required: true
        type: number
      num2:
        description: 'Second Number'
        required: true
        type: number

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Script
      #  continue-on-error: true
        id: run-script
        run: python sum.py ${{ github.event.inputs.num1 }} ${{ github.event.inputs.num2 }}

      #- name: Conditional step1
      #  if: failure() && steps.run-script.outcome == 'failure'
      #  run: echo "step 1 is running"

      #- name: Conditional step2
      #  if: success() 
      #  run: echo "step 2 is running"
  
  conditional-job-1:
    needs: run-python
    if: failure()
    runs-on: ubuntu-latest

      steps:
        - name: Conditional job1
          run: echo "Conditional job 1 is running"

  conditional-job-2:
    needs: run-python
    if: success()
    runs-on: ubuntu-latest

      steps:
        - name: Conditional job2
          run: echo "Conditional job 2 is running"
