name: Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      num1:
        description: 'First Number'
        required: true
      num2:
        description: 'Second Number'
        required: true

jobs:
  calculate-sum:
    runs-on: ubuntu-latest

  #  steps:
  #    - name: Call Calculate Sum Workflow
  #      uses: ./.github/workflows/callable.yml
  
  #      with:
  #       num1: ${{ github.event.inputs.num1 }}
  #        num2: ${{ github.event.inputs.num2 }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
          with:
            python-version: '3.10'
      - name: Run Python Script
        run: python sum.py ${{ github.event.inputs.num1 }} ${{ github.event.inputs.num2 }}
