name: Push Workflow

on:
  push:
    branches:
      - master

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Call Calculate Sum Workflow
        uses: ./.github/workflows/callable.yml
  
        with:
          num1: ${{ github.event.inputs.num1 }}
          num2: ${{ github.event.inputs.num2 }}