name: Secret Sum Workflow

on:
  push:
    branches:
      - master


jobs:
  run_python:
    runs-on: ubuntu-latest

    env:
      NUM1: ${{ secrets.NUM1 }}
      NUM2: ${{ secrets.NUM2 }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Calculate Sum
        run: |
          result=$(python sum.py ${{ env.NUM1 }} ${{ env.NUM2 }})
          echo "SUM_RESULT=$result" >> $GITHUB_ENV

      - name: Print Sum
        run: |
          echo "The Sum Result = $SUM_RESULT"